// Deterministic rules. All balance data lives here.
export const ASPECTS={Earth:['stone','brace'],Domination:['crush','firm'],Hex:['jinx','ward'],Restoration:['spirit','shelter'],Frost:['chill','cover'],Marksmanship:['steady','evade']};
const card=(name,aspect,mana,text,effect,spell=false)=>({name,aspect,mana,text,effect,spell});
export const CARDS={
stone:card('Stone Strike','Earth',0,'Deal 4 damage. Weaken the next attack by 1.',{damage:4,weak:1}),brace:card('Brace','Earth',0,'Gain 5 block.',{block:5}),crush:card('Crushing Blow','Domination',0,'Deal 6 damage.',{damage:6}),firm:card('Stand Firm','Domination',0,'Gain 4 block.',{block:4}),
jinx:card('Jinx','Hex',0,'Deal 3 damage. Apply 1 Curse.',{damage:3,curse:1}),ward:card('Warding Sign','Hex',0,'Gain 4 block.',{block:4}),spirit:card('Spirit Strike','Restoration',0,'Deal 5 damage.',{damage:5}),shelter:card('Shelter','Restoration',0,'Gain 5 block.',{block:5}),
chill:card('Chilling Shot','Frost',0,'Deal 4 damage. Weaken the next attack by 1.',{damage:4,weak:1}),cover:card('Ice Cover','Frost',0,'Gain 5 block.',{block:5}),steady:card('Steady Shot','Marksmanship',0,'Deal 5 damage.',{damage:5}),evade:card('Evasive Step','Marksmanship',0,'Gain 4 block.',{block:4}),
fissure:card('Fissure','Innate',2,'Deal 6 damage. Gain 6 block.',{damage:6,block:6},true),totem:card('Enchant Totem','Innate',2,'Your next attack this turn deals +9 damage.',{buff:9},true),slugger:card('Slugger','Innate',2,'Deal 10 damage, or 14 against an enemy at half health.',{damage:10,execute:4}),echo:card('Echo Slam','Ultimate',4,'Deal 20 damage. Gain 4 block.',{damage:20,block:4},true),
cask:card('Paralyzing Cask','Innate',0,'Deal 3 damage. Weaken the next attack by 2.',{damage:3,weak:2},true),voodoo:card('Voodoo Restoration','Innate',2,'Restore 7 health.',{heal:7},true),maledict:card('Maledict','Innate',2,'Apply 4 Curse.',{curse:4},true),deathward:card('Death Ward','Ultimate',3,'Deal 10 damage, plus 5 if the enemy is cursed.',{damage:10,cursedBonus:5},true),
frost:card('Frost Arrow','Innate',0,'Deal 4 damage. Weaken the next attack by 2.',{damage:4,weak:2}),gust:card('Gust','Innate',2,'Gain 10 block.',{block:10},true),multi:card('Multishot','Innate',3,'Deal 16 damage.',{damage:16},true),glacier:card('Glacier','Ultimate',4,'Gain 14 block. Attacks next turn deal +4 damage.',{block:14,nextBuff:4},true),
fault:card('Fault Line','Earth',2,'Deal 8 damage. Weaken the next attack by 3.',{damage:8,weak:3},true),slam:card('Heavy Slam','Domination',3,'Deal 17 damage.',{damage:17}),hex:card('Lingering Hex','Hex',2,'Apply 5 Curse.',{curse:5},true),shelterplus:card('Spirit Shelter','Restoration',2,'Gain 5 block. Restore 5 health.',{block:5,heal:5},true),snap:card('Cold Snap','Frost',2,'Deal 9 damage. Weaken the next attack by 5.',{damage:9,weak:5},true),pierce:card('Piercing Arrow','Marksmanship',2,'Deal 10 damage, ignoring block.',{damage:10,pierce:true})};
export const HEROES={earth:{name:'Earthshaker',symbol:'ES',color:'#dfaa60',aspects:['Earth','Domination'],hp:40,mana:12,str:15,int:5,agi:0,growth:[1,.5,.5],innate:['fissure','totem','slugger'],ult:'echo',passive:'Aftershock',passiveText:'Every spell cast deals 2 extra damage and grants 3 block.',style:'Control the fight. Make every spell count.'},witch:{name:'Witch Doctor',symbol:'WD',color:'#b59ae8',aspects:['Hex','Restoration'],hp:32,mana:15,str:5,int:15,agi:5,growth:[.5,1,.5],innate:['cask','voodoo','maledict'],ult:'deathward',passive:'Gris-gris',passiveText:'Once per run, resurrect at half maximum health and mana.',style:'Curse your enemies. Borrow a second life.'},drow:{name:'Drow Ranger',symbol:'DR',color:'#80cbdc',aspects:['Frost','Marksmanship'],hp:28,mana:10,str:5,int:5,agi:10,growth:[.5,.5,1],innate:['frost','gust','multi'],ult:'glacier',passive:'Marksmanship',passiveText:'Take no health damage this round to gain 10 agility next turn. Does not stack.',style:'Stay untouched. Keep the better hand.'}};
export const RELICS={heart:{name:'Stout Heart',text:'+6 maximum health.'},reservoir:{name:'Deep Reservoir',text:'+3 maximum mana.'},explorer:{name:"Explorer’s Charm",text:'Every fourth new tile restores 2 extra health.'},battle:{name:'Battle Charm',text:'Start each fight with 3 block.'}};
export const ITEMS={heal:{name:'Healing Draught',text:'Restore 8 health.'},mana:{name:'Mana Draught',text:'Restore 4 mana.'},bomb:{name:'Blast Charge',text:'Deal 8 damage in combat.'}};
// Walls partition a broad ring and interconnecting lanes, not a perfect maze.
export const TERRAIN=['..........','..##..#...','......#...','.#..#.....','.#..#..#..','....#.....','..#...##..','..#.......','.....#....','..........'];
const ENCOUNTERS=[[2,0,'melee'],[4,1,'ranged'],[1,2,'armor'],[3,3,'melee'],[6,0,'ranged'],[5,4,'armor'],[2,5,'melee'],[7,3,'ranged'],[8,5,'armor'],[4,7,'melee'],[7,7,'ranged'],[8,8,'armor'],[4,3,'elite'],[5,6,'elite'],[8,2,'elite']];
export function makeMap(){let m=TERRAIN.flatMap((row,y)=>[...row].map((c,x)=>({x,y,wall:c==='#',seen:false,type:'empty',done:false})));const put=(x,y,type,enemy)=>Object.assign(m[y*10+x],{wall:false,type,enemy});for(const [x,y,e] of ENCOUNTERS)put(x,y,'enemy',e);put(0,5,'home');put(9,5,'boss','boss');put(0,2,'event');put(3,8,'event');put(7,9,'event');put(3,0,'treasure');put(0,8,'treasure');put(9,1,'treasure');put(5,9,'shrine');return m;}
export const ENEMIES={melee:{name:'Melee Creep',hp:18,pattern:[4,6]},ranged:{name:'Ranged Creep',hp:16,pattern:[3,7]},armor:{name:'Armored Creep',hp:24,pattern:['block',7]},elite:{name:'Siege Golem',hp:38,pattern:[0,12,6]},boss:{name:'Ancient Warden',hp:76,pattern:[6,'block',12]}};
export function stats(s){let h=HEROES[s.hero],n=s.level-1;let str=h.str+n*h.growth[0],int=h.int+n*h.growth[1],agi=h.agi+n*h.growth[2]+(s.combat?.agile?10:0);return {str,int,agi,draw:4+Math.floor(agi/10),heal:Math.floor(str/5),mana:Math.floor(int/10)};}
function rng(s){s.seed=(Math.imul(s.seed,1664525)+1013904223)>>>0;return s.seed/4294967296;}
function shuffle(s,arr){let a=[...arr];for(let i=a.length-1;i>0;i--){let j=Math.floor(rng(s)*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function log(s,t){s.log=[t,...s.log].slice(0,80);}
function restore(s,h,m){const hp=s.hp,mp=s.mana;s.hp=Math.min(s.maxHp,s.hp+h);s.mana=Math.min(s.maxMana,s.mana+m);s.metrics.heal+=s.hp-hp;s.metrics.mana+=s.mana-mp;s.metrics.overflow+=h-(s.hp-hp)+m-(s.mana-mp);return [s.hp-hp,s.mana-mp];}
function reveal(s){let count=0;for(let y=Math.max(0,s.y-1);y<=Math.min(9,s.y+1);y++)for(let x=Math.max(0,s.x-1);x<=Math.min(9,s.x+1);x++){let t=s.map[y*10+x];if(!t.seen){t.seen=true;count++;s.explored++;if(s.relics.includes('explorer')){s.charmCount++;if(s.charmCount%4===0)restore(s,2,0);}}}if(count){let [h,m]=restore(s,count,count*.5);log(s,`Revealed ${count} tiles · +${h} HP · +${m} mana`);}}
export function createRun(hero,seed=1729){if(!HEROES[hero])throw Error('Unknown hero');let h=HEROES[hero];let s={hero,seed:seed>>>0,initialSeed:seed>>>0,level:1,hp:h.hp,maxHp:h.hp,mana:h.mana,maxMana:h.mana,deck:[...h.innate,...h.aspects.flatMap(a=>ASPECTS[a].flatMap(c=>[c,c]))],x:0,y:5,map:makeMap(),phase:'map',combat:null,reward:null,relics:[],items:['heal','mana'],gris:true,explored:0,charmCount:0,kills:0,log:[],history:[],metrics:{spent:0,heal:0,mana:0,overflow:0,turns:0,passives:0},started:Date.now()};reveal(s);log(s,`${h.name} arrives at the friendly Ancient.`);return s;}
function draw(s){let c=s.combat;for(let i=0;i<stats(s).draw;i++){if(!c.pile.length){c.pile=shuffle(s,c.discard);c.discard=[];}if(c.pile.length)c.hand.push(c.pile.pop());}}
function startFight(s,t){let e=ENEMIES[t.enemy];s.phase='combat';s.combat={tile:t.y*10+t.x,key:t.enemy,name:e.name,hp:e.hp,maxHp:e.hp,enemyBlock:0,weak:0,curse:0,turn:1,actions:2,block:s.relics.includes('battle')?3:0,hand:[],pile:shuffle(s,s.deck),discard:[],buff:0,nextBuff:0,turnBuff:0,agile:false,damaged:false,itemUsed:false};draw(s);log(s,`Combat: ${e.name}.`);}
export function intent(s){let c=s.combat;if(!c)return null;let v=ENEMIES[c.key].pattern[(c.turn-1)%ENEMIES[c.key].pattern.length];return v==='block'?{kind:'block',amount:c.key==='boss'?6:5,label:'Fortify'}:{kind:'attack',amount:Math.max(0,v-c.weak),label:v===0?'Charging':'Attack'};}
function damageEnemy(s,n,pierce=false){let c=s.combat;if(!pierce){let absorbed=Math.min(c.enemyBlock,n);c.enemyBlock-=absorbed;n-=absorbed;}c.hp=Math.max(0,c.hp-n);}
function addRelic(s,id){if(s.relics.includes(id))return;s.relics.push(id);if(id==='heart')s.maxHp+=6;if(id==='reservoir')s.maxMana+=3;log(s,`Relic acquired: ${RELICS[id].name}.`);}
function options(s){let h=HEROES[s.hero];return [h.innate[Math.floor(rng(s)*h.innate.length)],...h.aspects.map(a=>{let pool=Object.keys(CARDS).filter(k=>CARDS[k].aspect===a&&!ASPECTS[a].includes(k));return pool[Math.floor(rng(s)*pool.length)];})];}
function finishFight(s){let c=s.combat;if(c.hp>0)return;let t=s.map[c.tile];t.done=true;s.kills++;let st=stats(s);let [h,m]=restore(s,st.heal,st.mana);log(s,`Victory · +${h} HP · +${m} mana.`);s.combat=null;if(c.key==='boss'){s.phase='won';return;}s.level++;let elite=c.key==='elite';if(s.level===6){s.deck.push(HEROES[s.hero].ult);s.reward={kind:'ultimate',cards:[HEROES[s.hero].ult],elite};}else{s.reward={kind:'cards',cards:options(s),elite};}s.phase='reward';}
function nextReward(s){let elite=s.reward?.elite;s.reward=null;if(elite){let pool=Object.keys(RELICS).filter(k=>!s.relics.includes(k));if(pool.length){s.reward={kind:'relic',cards:shuffle(s,pool).slice(0,2)};s.phase='reward';return;}}s.phase='map';}
function hurt(s,n){let c=s.combat,absorb=Math.min(c.block,n);c.block-=absorb;n-=absorb;if(n>0)c.damaged=true;s.hp=Math.max(0,s.hp-n);if(s.hp===0){if(s.hero==='witch'&&s.gris){s.gris=false;s.hp=Math.ceil(s.maxHp/2);s.mana=Math.ceil(s.maxMana/2);s.metrics.passives++;log(s,'Gris-gris awakens. Restored to half health and mana.');}else{s.phase='lost';log(s,'Your hero has fallen.');}}}
// Route only through revealed terrain. Living enemies may be the destination, never a shortcut.
export function pathTo(s,x,y){
 if(s.phase!=='map')throw Error('Finish this encounter first');
 if(!Number.isInteger(x)||!Number.isInteger(y)||x<0||x>9||y<0||y>9)throw Error('Invalid destination');
 const target=y*10+x;if(!s.map[target].seen||s.map[target].wall)throw Error('Choose a revealed path');
 const start=s.y*10+s.x,q=[start],routes=new Map([[start,[]]]);
 while(q.length){const idx=q.shift();if(idx===target)return routes.get(idx);const t=s.map[idx];
  for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=t.x+dx,ny=t.y+dy;if(nx<0||nx>9||ny<0||ny>9)continue;const n=ny*10+nx,cell=s.map[n];
   if(routes.has(n)||!cell.seen||cell.wall||(cell.enemy&&!cell.done&&n!==target))continue;
   routes.set(n,[...routes.get(idx),{type:'move',x:nx,y:ny}]);q.push(n);
  }
 }
 throw Error('No revealed route to that tile');
}
export function reduce(input,action){
if(action?.type==='navigate'){const route=pathTo(input,action.x,action.y);let result=structuredClone(input);for(const step of route){result=reduce(result,step);if(result.phase!=='map')break;}return result;}
let s=structuredClone(input);if(!s||!action)throw Error('Invalid action');s.history.push(action);const c=s.combat;
if(action.type==='move'){if(s.phase!=='map')throw Error('Finish this encounter first');let {x,y}=action;if(!Number.isInteger(x)||!Number.isInteger(y)||x<0||y<0||x>9||y>9||Math.abs(s.x-x)+Math.abs(s.y-y)!==1)throw Error('Move one adjacent step');let t=s.map[y*10+x];if(!t.seen||t.wall)throw Error('Choose a revealed path');const previous={x:s.x,y:s.y};s.x=x;s.y=y;reveal(s);if(!t.done){if(t.type==='enemy'||t.type==='boss'){s.phase='approach';s.approach={tile:y*10+x,previous};log(s,`${ENEMIES[t.enemy].name} encountered.`);}else if(t.type==='event'){s.phase='event';s.reward={kind:(x+y)%2?'training':'cache',tile:y*10+x};}else if(t.type==='shrine'){s.phase='event';s.reward={kind:'shrine',tile:y*10+x};}else if(t.type==='treasure'){t.done=true;let relic=Object.keys(RELICS).find(k=>!s.relics.includes(k));if((x+y)%2&&relic){addRelic(s,relic);}else{s.phase='reward';s.reward={kind:'item',cards:[['heal','mana','bomb'][Math.floor(rng(s)*3)]]};}}}}
else if(action.type==='encounter'){if(s.phase!=='approach'||!s.approach)throw Error('No enemy encounter');if(!['fight','retreat'].includes(action.choice))throw Error('Choose fight or retreat');const pending=s.approach;s.approach=null;if(action.choice==='retreat'){s.x=pending.previous.x;s.y=pending.previous.y;s.phase='map';log(s,'Retreated.');}else startFight(s,s.map[pending.tile]);}
else if(action.type==='play'){if(s.phase!=='combat'||!c)throw Error('Not in combat');let idx=action.index,id=c.hand[idx],card=CARDS[id];if(!card||!Number.isInteger(idx))throw Error('Choose a card in hand');if(c.actions<1||s.mana<card.mana)throw Error('Not enough actions or mana');c.actions--;s.mana-=card.mana;s.metrics.spent+=card.mana;c.hand.splice(idx,1);let e=card.effect;if(e.damage){damageEnemy(s,e.damage+(e.execute&&c.hp<=c.maxHp/2?e.execute:0)+(e.cursedBonus&&c.curse?e.cursedBonus:0)+c.buff+c.turnBuff,e.pierce);c.buff=0;}if(e.block)c.block+=e.block;if(e.weak)c.weak=Math.max(c.weak,e.weak);if(e.curse)c.curse+=e.curse;if(e.heal)restore(s,e.heal,0);if(e.buff)c.buff=e.buff;if(e.nextBuff)c.nextBuff=e.nextBuff;c.discard.push(id);log(s,`Played ${card.name}.`);if(s.hero==='earth'&&card.spell){c.block+=3;damageEnemy(s,2);s.metrics.passives++;log(s,'Aftershock · 2 damage + 3 block.');}finishFight(s);}
else if(action.type==='end'){if(s.phase!=='combat'||!c)throw Error('Not in combat');let i=intent(s);c.discard.push(...c.hand);c.hand=[];c.enemyBlock=0;if(i.kind==='block')c.enemyBlock=i.amount;else{hurt(s,i.amount);c.weak=0;}s.metrics.turns++;log(s,`${c.name}: ${i.label}${i.amount?' '+i.amount:''}.`);if(s.phase==='lost')return s;if(c.curse){damageEnemy(s,c.curse,true);c.curse--;}finishFight(s);if(!s.combat)return s;c.agile=s.hero==='drow'&&!c.damaged;if(c.agile)s.metrics.passives++;c.damaged=false;c.turn++;c.actions=2;c.block=0;c.buff=0;c.turnBuff=c.nextBuff;c.nextBuff=0;c.itemUsed=false;draw(s);}
else if(action.type==='item'){if(!['map','combat'].includes(s.phase))throw Error('Items unavailable now');let idx=action.index,id=s.items[idx];if(!id)throw Error('No item');if(c?.itemUsed)throw Error('One item per turn');if(id==='bomb'&&!c)throw Error('Use in combat');s.items.splice(idx,1);if(c)c.itemUsed=true;if(id==='heal')restore(s,8,0);if(id==='mana')restore(s,0,4);if(id==='bomb')damageEnemy(s,8);log(s,`Used ${ITEMS[id].name}.`);if(c)finishFight(s);}
else if(action.type==='reward'){if(s.phase!=='reward')throw Error('No reward');let r=s.reward,id=action.id;if(r.kind==='cards'){if(id!==null&&!r.cards.includes(id))throw Error('Invalid reward');if(id)s.deck.push(id);nextReward(s);}else if(r.kind==='ultimate'){nextReward(s);}else if(r.kind==='relic'){if(!r.cards.includes(id))throw Error('Choose a relic');addRelic(s,id);nextReward(s);}else if(r.kind==='item'){if(id!==null){if(!r.cards.includes(id))throw Error('Invalid item');if(s.items.length>=2){if(!Number.isInteger(action.replace)||action.replace<0||action.replace>1)throw Error('Choose an item to replace');s.items.splice(action.replace,1);}s.items.push(id);}nextReward(s);}}
else if(action.type==='event'){if(s.phase!=='event')throw Error('No event');let r=s.reward;if(action.choice!=='leave'){if(r.kind==='training'){if(s.deck.length<=6||!Number.isInteger(action.index)||!s.deck[action.index])throw Error('Choose a card');s.deck.splice(action.index,1);}else if(r.kind==='cache'){if(s.hp<=6)throw Error('Need more than 6 health');s.hp-=6;s.map[r.tile].done=true;s.reward={kind:'cards',cards:options(s)};s.phase='reward';return s;}else if(r.kind==='shrine'){if(!['heal','mana'].includes(action.choice))throw Error('Choose recovery');restore(s,action.choice==='heal'?8:0,action.choice==='mana'?4:0);}}s.map[r.tile].done=true;s.reward=null;s.phase='map';}
else throw Error('Unknown action');return s;}
// Public view deliberately omits hidden contents, random state, and future draws.
export function publicState(s){return {hero:s.hero,phase:s.phase,level:s.level,hp:s.hp,mana:s.mana,stats:stats(s),position:[s.x,s.y],map:s.map.map(t=>t.seen?t:{x:t.x,y:t.y,seen:false}),approach:s.approach?{enemy:ENEMIES[s.map[s.approach.tile].enemy],previous:s.approach.previous}:null,hand:s.combat?.hand,intent:intent(s),reward:s.reward};}
